### ISSUE TITLE
migrate project to playframework 2.8

### ISSUE THREAD

**Issue by GarnicaJR** [stevenzearo/play-gradle#1]
Hi Steven,

play-gradle will support play framework 2.98 or not yet? 

Thanks
Jose Garnica.

**Comment by stevenzearo** [comment]
I'm sorry for reply too late.
Cause of this project is base on a plugin which git repo is https://gradle.github.io/playframework/ and the plugin supported Play versions are 2.4.x, 2.5.x and 2.6.x.
So I'm not sure if this project will support play framework 2.98.
This project is a test project for using playframework.
If there is any idea of developing an opensource playframework relevant project, I will be very glade to join.
Thanks
Steve Zou.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"GarnicaJR"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 凌晨4:47
收件人:&nbsp;"stevenzearo/play-gradle"<play-gradle@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[stevenzearo/play-gradle] migrate project to playframework 2.8 (#1)





 
Hi Steven,
 
play-gradle will support play framework 2.98 or not yet?
 
Thanks
 Jose Garnica.

**Comment by stevenzearo** [comment]
> 
> 
> Hi Steven,
> 
> play-gradle will support play framework 2.98 or not yet?
> 
> Thanks
> Jose Garnica.

Currently, paly framework was upgraded to 2.8.8
